name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alembic=1.4.1
  - appdirs=1.4.4
  - arrow-cpp=6.0.1
  - asn1crypto=1.4.0
  - async-timeout=4.0.1
  - attrs=21.2.0
  - aws-c-auth=0.6.8
  - aws-c-cal=0.5.12
  - aws-c-common=0.6.17
  - aws-c-compression=0.2.14
  - aws-c-event-stream=0.2.7
  - aws-c-http=0.6.10
  - aws-c-io=0.10.14
  - aws-c-mqtt=0.7.10
  - aws-c-s3=0.1.28
  - aws-c-sdkutils=0.1.1
  - aws-checksums=0.1.12
  - aws-crt-cpp=0.17.10
  - aws-sdk-cpp=1.9.160
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.9
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - configparser=5.2.0
  - cryptography=36.0.0
  - databricks-cli=0.12.1
  - dataclasses=0.8
  - datasets=1.16.1
  - dill=0.3.4
  - docker-py=5.0.3
  - docker-pycreds=0.4.0
  - entrypoints=0.3
  - filelock=3.4.0
  - flask=2.0.2
  - frozenlist=1.2.0
  - fsspec=2021.11.1
  - future=0.18.2
  - gflags=2.2.2
  - gitdb=4.0.9
  - gitpython=3.1.24
  - glog=0.5.0
  - greenlet=1.1.2
  - grpc-cpp=1.42.0
  - gunicorn=20.1.0
  - huggingface_hub=0.2.1
  - idna=3.1
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - itsdangerous=2.0.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - krb5=1.19.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libcxx=12.0.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libprotobuf=3.18.1
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libutf8proc=2.6.1
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - mako=1.1.6
  - markupsafe=2.0.1
  - mkl=2021.4.0
  - mlflow=1.22.0
  - multidict=5.2.0
  - multiprocess=0.70.12.2
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.21.4
  - openssl=1.1.1l
  - orc=1.7.1
  - packaging=21.3
  - pandas=1.3.4
  - parquet-cpp=1.5.1
  - pip=21.3.1
  - prometheus_client=0.12.0
  - prometheus_flask_exporter=0.18.6
  - protobuf=3.18.1
  - pyarrow=6.0.1
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python-xxhash=2.0.2
  - python_abi=3.8
  - pytorch=1.10.0
  - pytz=2021.3
  - pyyaml=6.0
  - querystring_parser=1.2.4
  - re2=2021.11.01
  - readline=8.1
  - regex=2021.11.10
  - requests=2.26.0
  - sacremoses=0.0.46
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - setuptools=59.4.0
  - six=1.16.0
  - sleef=3.5.1
  - smmap=3.0.5
  - snappy=1.1.8
  - sqlalchemy=1.4.27
  - sqlite=3.37.0
  - sqlparse=0.4.2
  - tabulate=0.8.9
  - tbb=2021.4.0
  - tenacity=8.0.1
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tokenizers=0.10.3
  - tqdm=4.62.3
  - transformers=4.12.5
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - urllib3=1.26.7
  - websocket-client=1.2.3
  - werkzeug=2.0.1
  - wheel=0.37.0
  - xxhash=0.8.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
