name: pytorch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pip
  - pip:
    - torch
    - transformers
    - datasets
    - pandas
    - numpy
    - scikit-learn
    - mlflow
  
